name: Build and Test ML API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t loan-default-api .

      - name: Run container
        run: docker run -d -p 8000:8000 --name ml-api loan-default-api

      - name: Wait for container to start
        run: sleep 20

      - name: Test health endpoint
        run: |
          curl --retry 3 --retry-delay 2 --fail http://localhost:8000/health

      - name: Test predict endpoint
        run: |
          curl --fail -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"credit_score": 700, "annual_income": 65000, "loan_amount": 20000, "debt_to_income": 18.5, "employment_length": 5, "home_ownership": "MORTGAGE", "loan_purpose": "debt_consolidation", "interest_rate": 12.0, "open_accounts": 10, "delinquencies_2yr": 0}'

      # This step will ONLY run if any of the above steps (like the curl tests) fail.
      - name: Dump Container Debug Information
        if: failure()
        run: |
          echo "=========================================="
          echo "          CONTAINER RUNTIME STATUS        "
          echo "=========================================="
          docker ps -a

          echo "=========================================="
          echo "          CONTAINER ENGINE LOGS           "
          echo "=========================================="
          docker logs ml-api

      - name: Stop container
        if: always()
        run: docker stop ml-api
